name: Code Coverage Analysis

on:
  push:
    branches:
      - main

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Добавьте шаги для генерации файла lcov.info здесь
      # Например, запуск тестов с помощью Jest или другого тестового фреймворка

      - name: Run tests and generate coverage
        run: |
          # Команды для запуска тестов и генерации файла lcov.info
          # Например:
          # npm run test -- --coverage --coverageReporters=lcov

      - name: Qlty Code Coverage Analysis
        uses: qltysh/qlty-action/coverage@main
        with:
          coverage-token: ${{ secrets.QLTY_COVERAGE_TOKEN }}
          files: coverage/lcov.info
